/**
 * worktimeCsvDocument.java
 *
 * This file was generated by MapForce 2022r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.mapforce.worktimeCsv;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class worktimeCsvDocument extends Table {
	protected ISerializer createSerializer() {
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(true);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header) {
		
		header.add(new ColumnSpecification("HL\u00d6_ID"));
		header.add(new ColumnSpecification("P\u00c4IV\u00c4"));
		header.add(new ColumnSpecification("TULO"));
		header.add(new ColumnSpecification("L\u00c4HT\u00d6"));
		header.add(new ColumnSpecification("LIS\u00c4TIEDOT"));
	}
	public worktimeCsvDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
		super( tableType,lineend);
	}
}



